version: '3.9'
services:
  roaf3d:
    container_name: roaf3d
    env_file: .env
    extends:
      file: ../../humble/compose.base.yaml
      service: humble
    network_mode: "host"
    volumes:
      - ./:/home/${USERNAME}/workspace:rw
  