version: '3.9'
services:
  humble:
    extends:
      file: ../compose.base.yaml
      service: nvidia_enable
    build:
      dockerfile: Dockerfile
      args:
        - USERNAME
        - USER_UID
        - USER_GID
        - DOCKER_HOST_IP
    image: lawskiy/ros:humble