version: '3.9'
services:
  roaf3d:
    container_name: roaf3d
    env_file: .env
    build:
      context: ../docker_things
      dockerfile: Dockerfile
      args:
        - USERNAME
        - USER_UID
        - USER_GID
    image: lawskiy/ros:humble
    user: "${USERNAME}"
    hostname: ${USER_HOSTNAME}-docker
    extra_hosts:
      - "localhost.localdomain:127.0.0.1"
      - "localhost:127.0.0.1"
      - "${USER_HOSTNAME}-docker:127.0.0.1"
    volumes:
      - ./:/home/${USERNAME}/workspace
      - ../docker_things/vscode_data:/home/${USERNAME}/.vscode-server
      - ${SSHDIR}:/home/${USERNAME}/.ssh
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/snd:/dev/snd
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=3
      - DISPLAY=:1 # 默认显示到主屏幕上
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    command: tail -f /dev/null # we need this to prevent container exit
  