version: '3.9'
services:
  px4_1.13.3:
    container_name: px4_1.13.3
    env_file: .env
    extends:
      file: ../../noetic/compose.base.yaml
      service: noetic
    network_mode: "host"
    volumes:
      - ./src/PX4-Autopilot:/home/${USERNAME}/workspace:rw
  